dist: trusty
sudo: false

env:
- LAUNCH_SCRIPT='run_cromwell.sh'
- LAUNCH_SCRIPT='run_cwltool.sh'
- LAUNCH_SCRIPT='run_bash.sh'

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq samtools cpanminus r-base

install: 
- cd gsi-website && perl Makefile.PL && make && make test && sudo make install && cd ..
- cd bamqc && cpanm --installdeps --sudo . && perl Makefile.PL && make && make test && sudo make install && cd ..


script:
- bash "${LAUNCH_SCRIPT}"
